# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/lab2/Basys3_test_env.xdc

# Block Designs: bd/BRAM2/BRAM2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM2 || ORIG_REF_NAME==BRAM2}]

# IP: bd/BRAM2/ip/BRAM2_blk_mem_gen_0_0/BRAM2_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BRAM2_blk_mem_gen_0_0 || ORIG_REF_NAME==BRAM2_blk_mem_gen_0_0}]

# XDC: bd/BRAM2/BRAM2_ooc.xdc
