# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/trian/Desktop/Practica/VGA_on_Fpga/VGA_on_Fpga.cache/wt [current_project]
set_property parent.project_path C:/Users/trian/Desktop/Practica/VGA_on_Fpga/VGA_on_Fpga.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/trian/Desktop/Practica/VGA_on_Fpga/VGA_on_Fpga.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/trian/Desktop/Practica/VGA_on_Fpga/VGA_on_Fpga.srcs/sources_1/new/bisD.vhd
  C:/Users/trian/Desktop/Practica/VGA_on_Fpga/VGA_on_Fpga.srcs/sources_1/new/register.vhd
  C:/Users/trian/Desktop/Practica/VGA_on_Fpga/VGA_on_Fpga.srcs/sources_1/new/I2C.vhd
  C:/Users/trian/Desktop/Practica/VGA_on_Fpga/VGA_on_Fpga.srcs/sources_1/imports/new/lab1p3.vhd
  C:/Users/trian/Desktop/Practica/VGA_on_Fpga/VGA_on_Fpga.srcs/sources_1/new/clock_div.vhd
  C:/Users/trian/Desktop/Practica/VGA_on_Fpga/VGA_on_Fpga.srcs/sources_1/new/VGA.vhd
  C:/Users/trian/Desktop/Practica/VGA_on_Fpga/VGA_on_Fpga.srcs/sources_1/new/Capture.vhd
  C:/Users/trian/Desktop/Practica/VGA_on_Fpga/VGA_on_Fpga.srcs/sources_1/new/controller.vhd
  C:/Users/trian/Desktop/Practica/VGA_on_Fpga/VGA_on_Fpga.srcs/sources_1/new/vga_on_fpga.vhd
}
add_files C:/Users/trian/Desktop/Practica/VGA_on_Fpga/VGA_on_Fpga.srcs/sources_1/bd/BRAM2/BRAM2.bd
set_property used_in_implementation false [get_files -all c:/Users/trian/Desktop/Practica/VGA_on_Fpga/VGA_on_Fpga.srcs/sources_1/bd/BRAM2/ip/BRAM2_blk_mem_gen_0_0/BRAM2_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/trian/Desktop/Practica/VGA_on_Fpga/VGA_on_Fpga.srcs/sources_1/bd/BRAM2/BRAM2_ooc.xdc]
set_property is_locked true [get_files C:/Users/trian/Desktop/Practica/VGA_on_Fpga/VGA_on_Fpga.srcs/sources_1/bd/BRAM2/BRAM2.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/trian/Desktop/Practica/VGA_on_Fpga/VGA_on_Fpga.srcs/constrs_1/imports/lab2/Basys3_test_env.xdc
set_property used_in_implementation false [get_files C:/Users/trian/Desktop/Practica/VGA_on_Fpga/VGA_on_Fpga.srcs/constrs_1/imports/lab2/Basys3_test_env.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top vga_on_fpga -part xc7a100tcsg324-1


write_checkpoint -force -noxdef vga_on_fpga.dcp

catch { report_utilization -file vga_on_fpga_utilization_synth.rpt -pb vga_on_fpga_utilization_synth.pb }
