# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Fonea/Desktop/AC MIPS/test_env/test_env.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Fonea/Desktop/AC MIPS/test_env/test_env.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/Fonea/Desktop/AC MIPS/test_env/test_env.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/Fonea/Desktop/AC MIPS/test_env/test_env.srcs/sources_1/imports/new/REGISTER_FILE.vhd}
  {C:/Users/Fonea/Desktop/AC MIPS/test_env/test_env.srcs/sources_1/new/EX.vhd}
  {C:/Users/Fonea/Desktop/AC MIPS/test_env/test_env.srcs/sources_1/new/MEM.vhd}
  {C:/Users/Fonea/Desktop/AC MIPS/test_env/test_env.srcs/sources_1/new/DecodeID.vhd}
  {C:/Users/Fonea/Desktop/AC MIPS/test_env/test_env.srcs/sources_1/new/Control_Unit.vhd}
  {C:/Users/Fonea/Desktop/AC MIPS/test_env/test_env.srcs/sources_1/imports/new/SSD.vhd}
  {C:/Users/Fonea/Desktop/AC MIPS/test_env/test_env.srcs/sources_1/imports/new/MPG.vhd}
  {C:/Users/Fonea/Desktop/AC MIPS/test_env/test_env.srcs/sources_1/imports/new/Instruction_Fetch.vhd}
  {C:/Users/Fonea/Desktop/AC MIPS/test_env/test_env.srcs/sources_1/new/test_env.vhd}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Fonea/Desktop/AC MIPS/test_env/test_env.srcs/constrs_1/imports/AC/Basys3_test_env.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Fonea/Desktop/AC MIPS/test_env/test_env.srcs/constrs_1/imports/AC/Basys3_test_env.xdc}}]


synth_design -top test_env -part xc7a35tcpg236-1


write_checkpoint -force -noxdef test_env.dcp

catch { report_utilization -file test_env_utilization_synth.rpt -pb test_env_utilization_synth.pb }
